config/routes.rb
MjTsumotterServer::Application.routes.draw do
  namespace :admin do resources :yakus end

  match 'agaris' => 'agaris#create', :via => :post

end

app/models/admin/yaku.rb
class Admin::Yaku < ActiveRecord::Base
  def attributes
    {'name' => name,
     'han_num' => han_num,
     'naki_han_num' => naki_han_num
    }
  end
end

app/controllers/admin/yakus_controller.rb
class Admin::YakusController < ApplicationController
  # GET /admin/yakus
  # GET /admin/yakus.json
  def index
    @admin_yakus = Admin::Yaku.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @admin_yakus }
    end
  end

  # GET /admin/yakus/1
  # GET /admin/yakus/1.json
  def show
    @admin_yaku = Admin::Yaku.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @admin_yaku }
    end
  end

  # GET /admin/yakus/new
  # GET /admin/yakus/new.json
  def new
    @admin_yaku = Admin::Yaku.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @admin_yaku }
    end
  end

  # GET /admin/yakus/1/edit
  def edit
    @admin_yaku = Admin::Yaku.find(params[:id])
  end

  # POST /admin/yakus
  # POST /admin/yakus.json
  def create
    @admin_yaku = Admin::Yaku.new(params[:admin_yaku])

    respond_to do |format|
      if @admin_yaku.save
        format.html { redirect_to @admin_yaku, notice: 'Yaku was successfully created.' }
        format.json { render json: @admin_yaku, status: :created, location: @admin_yaku }
      else
        format.html { render action: "new" }
        format.json { render json: @admin_yaku.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/yakus/1
  # PUT /admin/yakus/1.json
  def update
    @admin_yaku = Admin::Yaku.find(params[:id])

    respond_to do |format|
      if @admin_yaku.update_attributes(params[:admin_yaku])
        format.html { redirect_to @admin_yaku, notice: 'Yaku was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @admin_yaku.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/yakus/1
  # DELETE /admin/yakus/1.json
  def destroy
    @admin_yaku = Admin::Yaku.find(params[:id])
    @admin_yaku.destroy

    respond_to do |format|
      format.html { redirect_to admin_yakus_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin/yakus_helper.rb
module Admin::YakusHelper
end

app/views/admin/yakus/_form.html.erb
<%= form_for(@admin_yaku) do |f| %>
  <% if @admin_yaku.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_yaku.errors.count, "error") %> prohibited this admin_yaku from being saved:</h2>

      <ul>
      <% @admin_yaku.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :han_num %><br />
    <%= f.text_field :han_num %>
  </div>
  <div class="field">
    <%= f.label :naki_han_num %><br />
    <%= f.text_field :naki_han_num %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/yakus/edit.html.erb
<h1>Editing admin_yaku</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_yaku %> |
<%= link_to 'Back', admin_yakus_path %>

app/views/admin/yakus/index.html.erb
<h1>Listing admin_yakus</h1>

<table>
  <tr>
    <th>Name</th>
    <th>HanNum</th>
    <th>NakiHanNum</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @admin_yakus.each do |admin_yaku| %>
  <tr>
    <td><%= admin_yaku.name %></td>
    <td><%= admin_yaku.han_num %></td>
    <td><%= admin_yaku.naki_han_num %></td>
    <td><%= link_to 'Show', admin_yaku %></td>
    <td><%= link_to 'Edit', edit_admin_yaku_path(admin_yaku) %></td>
    <td><%= link_to 'Destroy', admin_yaku, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Yaku', new_admin_yaku_path %>

app/views/admin/yakus/new.html.erb
<h1>New admin_yaku</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_yakus_path %>

app/views/admin/yakus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @admin_yaku.name %>
</p>

<p>
  <b>Han num:</b>
  <%= @admin_yaku.han_num %>
</p>

<p>
  <b>Naki Han num:</b>
  <%= @admin_yaku.naki_han_num %>
</p>

<%= link_to 'Edit', edit_admin_yaku_path(@admin_yaku) %> |
<%= link_to 'Back', admin_yakus_path %>